# Generated by Django 6.0 on 2026-04-17 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portrait_requests', '0002_alter_portraitrequest_status'),
        ('profiles', '0003_alter_artistprofile_base_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_days', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='profiles.artistprofile')),
                ('portrait_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='portrait_requests.portraitrequest')),
            ],
        ),
    ]
