# Generated by Django 6.0.3 on 2026-04-06 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_alter_artistprofile_base_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortraitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('portrait_style', models.CharField(max_length=50)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='portrait_requests/')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_portrait_requests', to='profiles.artistprofile')),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_requests', to='profiles.clientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
