# Generated by Django 6.0 on 2026-04-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portraitrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('quote_sent', 'Quote Sent'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
