# Generated by Django 6.0 on 2026-05-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_staffprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
