# Generated by Django 6.0 on 2026-05-17 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0002_portfolioitem_likes_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItemLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='portfolio.portfolioitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio_item_likes',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'portfolio_item'), name='unique_user_portfolio_like')],
            },
        ),
    ]
