services:
  db:
    image: postgres:16
    container_name: craftit_db_container
    restart: always
    env_file:
      - ./backend/craftit_backend/.env
    environment:
      POSTGRES_DB: craftit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vithul
    ports:
      - "5432:5432"
    volumes:
      - craftit_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: craftit_redis_container
    restart: always
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:7
    container_name: craftit_mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - craftit_mongo_data:/data/db
      
  chat:
    build:
      context: ./chat-service
    container_name: craftit_chat_container
    restart: always
    command: sh -c "sleep 5 && daphne -b 0.0.0.0 -p 8001 config.asgi:application"
    volumes:
      - ./chat-service:/app
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - mongodb
    env_file:
      - ./chat-service/.env

  backend:
    build:
      context: ./backend/craftit_backend
    container_name: craftit_backend_container
    restart: always
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/craftit_backend:/app
    env_file:
      - ./backend/craftit_backend/.env
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend/craftit-web
    container_name: craftit_frontend_container
    restart: always
    volumes:
      - ./frontend/craftit-web:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  craftit_postgres_data:
    external: true
  craftit_mongo_data: