# Generated by Django 6.0 on 2026-05-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ARTIST', 'Artist'), ('CLIENT', 'Client')], max_length=10, null=True),
        ),
    ]
