# Generated by Django 6.0 on 2026-05-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_artistprofile_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='ranking_score',
            field=models.FloatField(default=0.0),
        ),
    ]
