# Generated by Django 6.0 on 2026-05-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_artistprofile_ranking_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='ranking_score',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
