# Generated by Django 6.0.3 on 2026-04-06 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_alter_artistprofile_base_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_clients', to='profiles.artistprofile')),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_artists', to='profiles.clientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('client_profile', 'artist_profile'), name='unique_saved_artist_per_client')],
            },
        ),
    ]
