# Generated by Django 6.0 on 2026-05-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
